# templates/mongodb.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongo.Name }}-deployment
spec:
  replicas: {{ .Values.mongo.statefulset.replicas }}
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: {{ .Values.mongo.image.registry }}/{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo.Name }}-mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: {{ .Values.mongo.service.port }}
      targetPort: 27017
