apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mongo
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: {{ .Values.mongo.statefulset.replicas }}
  serviceName: {{ .Release.Name }}-mongodb-headless
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.mongo.image.registry }}/{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}"
          imagePullPolicy: {{ .Values.mongo.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.mongo.service.port }}
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
      spec:
        accessModes: [ "{{ .Values.mongo.volumeClaimTemplates.accessModes }}" ]
        resources:
          requests:
            storage: "{{ .Values.mongo.volumeClaimTemplates.resources.requests.storage }}"

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo.name }}-headless
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: {{ .Values.mongo.service.port }}
