apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: Helm
    repoURL: 'https://github.com/MayaAsh02/To-Do-app.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default