nameOverride: ""
mongo:
  name: mongo
  image:
    registry: docker.io
    repository: mvertes/alpine-mongo
    tag: latest
  imagePullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 27017
  statefulset:
    replicas: 1
  volumeClaimTemplates:
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: 20Gi
flaskapp:
  name: flaskapp
  env: production
  image:
    name: flaskapp
    registry: docker.io
    repository: mayaashkinazi/todo-flaskapp
    tag: latest
  imagePullPolicy: Always
  service:
    port: 80
    targetPort: 5000
    type: LoadBalancer
ingress:
  host: todo-app.local
secrets:
  name: mongo-atlas-secret
  type: Opaque
  data:
    atlas-connection-string: files/.env
configMaps:
  name: metallb-config
  data:
    config: |-
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 192.168.99.200-192.168.99.220
app:
  image:
    tag: main-46ad5c2
